spring:
  datasource:
    url: jdbc:sqlserver://ravibaka-sqlserver.database.windows.net:1433;database=ravibaka-sqlserver;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: ravibaka
    password: Password1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191