spring:
  datasource:
    url: jdbc:sqlserver://user-sqlserver.database.windows.net:1433;database=user-sqlserver;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: user
    password: pass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191
